### ISSUE TITLE
Proton-5.21-GE-1 no longer available for download

### ISSUE THREAD

**Issue by daddeltrotter** [ChimeraOS/chimera-data#16]
The link https://github.com/GloriousEggroll/proton-ge-custom/releases/download/5.21-GE-1/Proton-5.21-GE-1.tar.gz isn't working  anymore. I haven't found any download anymore. 
Under https://github.com/GloriousEggroll/proton-ge-custom/releases/tag/5.21-GE-1 there is only the source code available.

**Comment by alkazar** [comment]
Nice catch. I will remove it and drop the games that use it.
