### ISSUE TITLE
Is it possible to show (or apply custom) icons for epic store games and flathub apps in the deck UI?

### ISSUE THREAD

**Issue by henry-low** [ChimeraOS/chimera-data#48]
By icons I mean the small/medium square images (ex: [link](https://cdn2.steamgriddb.com/file/sgdb-cdn/icon/bd6a06f41bae67be959e5b44addc880f.png)). When we quit a game by clicking on the "xbox" button on the xbox controller through the left menu, we'll see the icon there. Currently, for every epic store game or flathub app, this icon seems always blank. 

1. I wonder if there is any plan to auto scrape these icons?
2. Also, I wonder if it is possible to add support to apply custom icons similar to background, banner, poster and logo? (ex: to have a folder called icon under `/home/gamer/.local/share/chimera/images`. 

Thanks!

**Comment by alkazar** [comment]
You should be able to set an icon through the gamedb.yaml file. Steam does not provide a way to access the icon file like it does for the other art assets, so it has to be sourced from elsewhere.
